# Generated by Django 5.2.8 on 2026-01-13 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='#FFD700', max_length=20)),
                ('badge_type', models.CharField(choices=[('essays', 'Essay Writing'), ('likes', 'Popularity'), ('score', 'Quality'), ('competition', 'Competitions'), ('streak', 'Consistency'), ('community', 'Community')], max_length=50)),
                ('requirement_value', models.IntegerField(help_text='Value needed to earn this badge')),
                ('level', models.IntegerField(default=1, help_text='Badge level (1-5)')),
            ],
            options={
                'ordering': ['level', 'badge_type'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReviewTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('grammar', 'Grammar'), ('spelling', 'Spelling'), ('structure', 'Structure'), ('content', 'Content'), ('vocabulary', 'Vocabulary')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('correction', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_challenges_completed', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('timed_challenges_completed', models.IntegerField(default=0)),
                ('character_challenges_completed', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('last_challenge_date', models.DateField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points', '-total_challenges_completed'],
            },
        ),
        migrations.CreateModel(
            name='CharacterChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('character_limit', models.IntegerField(choices=[(100, '100 Characters - Micro'), (280, '280 Characters - Tweet'), (500, '500 Characters - Flash'), (1000, '1000 Characters - Short'), (2000, '2000 Characters - Medium')], default=280)),
                ('allow_over_limit', models.BooleanField(default=False)),
                ('points_reward', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_character_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('theme', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('general', 'General'), ('education', 'Education'), ('technology', 'Technology'), ('environment', 'Environment'), ('science', 'Science'), ('literature', 'Literature'), ('creative', 'Creative Writing'), ('argumentative', 'Argumentative'), ('narrative', 'Narrative'), ('descriptive', 'Descriptive')], default='general', max_length=50)),
                ('word_limit_min', models.IntegerField(default=300)),
                ('word_limit_max', models.IntegerField(default=1500)),
                ('time_limit_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('judging', 'Judging'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('formatted_content', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('education', 'Education'), ('technology', 'Technology'), ('environment', 'Environment'), ('science', 'Science'), ('literature', 'Literature'), ('creative', 'Creative Writing'), ('argumentative', 'Argumentative'), ('narrative', 'Narrative'), ('descriptive', 'Descriptive')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('word_count', models.IntegerField(default=0)),
                ('character_count', models.IntegerField(default=0)),
                ('sentence_count', models.IntegerField(default=0)),
                ('paragraph_count', models.IntegerField(default=0)),
                ('emoji_feedback', models.CharField(blank=True, choices=[('🌟', '🌟 Excellent - Outstanding work!'), ('👍', '👍 Good - Well done!'), ('✅', '✅ Satisfactory - Meets expectations'), ('📝', '📝 Needs Improvement - Some areas to work on'), ('💡', '💡 Creative - Great ideas!'), ('🚀', '🚀 Impressive - Above and beyond'), ('🎯', '🎯 On Target - Meets all requirements'), ('🔥', '🔥 Amazing work!'), ('💫', '💫 Exceptional effort'), ('✨', '✨ Well crafted')], help_text='Overall feedback emoji', max_length=5, null=True)),
                ('views', models.IntegerField(default=0)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('grammar_errors', models.TextField(blank=True)),
                ('spelling_errors', models.TextField(blank=True)),
                ('vocabulary_suggestions', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('grammar_status', models.CharField(choices=[('pending', 'Pending'), ('checked', 'Checked'), ('needs_review', 'Needs Review'), ('auto_approved', 'Auto Approved')], default='pending', max_length=20)),
                ('grammar_score', models.DecimalField(blank=True, decimal_places=2, help_text='Grammar score from 0-100', max_digits=5, null=True)),
                ('grammar_checked_at', models.DateTimeField(blank=True, null=True)),
                ('grammar_notes', models.TextField(blank=True, help_text='Admin notes on grammar issues')),
                ('requires_grammar_check', models.BooleanField(default=False, help_text='User requested grammar check')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to=settings.AUTH_USER_MODEL)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarked_essays', to=settings.AUTH_USER_MODEL)),
                ('grammar_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_essays', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_essays', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_essays', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_essays', to=settings.AUTH_USER_MODEL)),
                ('primary_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essay.language')),
            ],
            options={
                'verbose_name_plural': 'Essays',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('won_prize', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='essay.competition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_submissions', to=settings.AUTH_USER_MODEL)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_submissions', to='essay.essay')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='essay.comment')),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='essay.essay')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIWritingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(choices=[('improve', 'Improve Text'), ('expand', 'Expand Content'), ('summarize', 'Summarize'), ('rephrase', 'Rephrase'), ('grammar', 'Grammar Check'), ('tone', 'Adjust Tone'), ('creative', 'Creative Suggestions')], max_length=20)),
                ('original_text', models.TextField()),
                ('ai_suggestion', models.TextField()),
                ('was_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
                ('essay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='essay.essay')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrammarCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('issues_found', models.IntegerField(default=0)),
                ('issues_data', models.JSONField(blank=True, default=dict)),
                ('suggestions', models.TextField(blank=True)),
                ('automated_check', models.BooleanField(default=False)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_checks', to='essay.essay')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('comment', 'New Comment'), ('like', 'New Like'), ('system', 'System Notification'), ('achievement', 'Achievement Unloaded'), ('essay_published', 'Essay Published'), ('reply', 'Reply to Comment'), ('competition_start', 'Competition Started'), ('competition_result', 'Competition Result'), ('follow', 'New Follower')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('is_actionable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimedChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.TextField(help_text='The writing prompt for this challenge')),
                ('duration_minutes', models.IntegerField(choices=[(15, '15 Minutes - Sprint'), (30, '30 Minutes - Quick Write'), (60, '60 Minutes - Standard'), (120, '2 Hours - Extended'), (180, '3 Hours - Marathon')], default=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('min_words', models.IntegerField(default=300)),
                ('max_words', models.IntegerField(default=1000)),
                ('points_reward', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_timed_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Administrator')], default='student', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/%Y/%m/')),
                ('experience_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('email_competition_updates', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badges', models.ManyToManyField(blank=True, related_name='users', to='essay.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='CharacterChallengeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('character_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('is_valid', models.BooleanField(default=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='essay.characterchallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('challenge', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_set', to=settings.AUTH_USER_MODEL)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_set', to='essay.essay')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'essay')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paragraph_number', models.IntegerField()),
                ('content', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('character_count', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='essay.essay')),
            ],
            options={
                'ordering': ['paragraph_number'],
                'unique_together': {('essay', 'paragraph_number')},
            },
        ),
        migrations.CreateModel(
            name='TimedChallengeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='essay.timedchallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timed_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('challenge', 'user', 'started_at')},
            },
        ),
    ]
