# Generated by Django 5.2.8 on 2025-12-23 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('writing', 'Writing in Progress'), ('submitted', 'Submitted'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('word_count', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('general', 'General'), ('education', 'Education'), ('technology', 'Technology'), ('environment', 'Environment'), ('creative', 'Creative Writing')], default='general', max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='essays/pdfs/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('grammar_issues', models.PositiveIntegerField(default=0)),
                ('spelling_issues', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('grammar_score', models.FloatField(default=0.0)),
                ('spelling_score', models.FloatField(default=0.0)),
                ('content_score', models.FloatField(default=0.0)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('unique_words', models.IntegerField(default=0)),
                ('sentence_count', models.IntegerField(default=0)),
                ('avg_sentence_length', models.FloatField(default=0.0)),
                ('leaderboard_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_essays', to=settings.AUTH_USER_MODEL)),
                ('primary_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_essays', to='essay.language')),
            ],
            options={
                'verbose_name_plural': 'Essays',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='essay.essay')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('judge', 'Judge')], default='student', max_length=10)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('total_essays', models.IntegerField(default=0)),
                ('total_likes_received', models.IntegerField(default=0)),
                ('avg_essay_score', models.FloatField(default=0.0)),
                ('leaderboard_score', models.FloatField(default=0.0)),
                ('last_score_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essay.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paragraph_number', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('word_count', models.IntegerField(default=0)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='essay.essay')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essay.language')),
            ],
            options={
                'ordering': ['paragraph_number'],
                'unique_together': {('essay', 'paragraph_number')},
            },
        ),
    ]
