# Generated by Django 5.2.8 on 2025-12-19 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('file_name', models.CharField(default='essay.txt', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('writing', 'Writing in Progress'), ('submitted', 'Submitted'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('word_count', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('general', 'General'), ('education', 'Education'), ('technology', 'Technology'), ('environment', 'Environment'), ('creative', 'Creative Writing')], default='general', max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='essays/pdfs/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('writing_mode', models.CharField(choices=[('normal', 'Normal'), ('paragraph', 'Paragraph by Paragraph')], default='normal', max_length=20)),
                ('current_paragraph', models.PositiveIntegerField(default=1)),
                ('max_paragraphs', models.PositiveIntegerField(default=5)),
                ('grammar_issues', models.PositiveIntegerField(default=0)),
                ('spelling_issues', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('grammar_score', models.FloatField(default=0.0)),
                ('spelling_score', models.FloatField(default=0.0)),
                ('content_score', models.FloatField(default=0.0)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('unique_words', models.IntegerField(default=0)),
                ('sentence_count', models.IntegerField(default=0)),
                ('avg_sentence_length', models.FloatField(default=0.0)),
                ('leaderboard_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_essays', to=settings.AUTH_USER_MODEL)),
                ('primary_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_essays', to='essay.language')),
            ],
            options={
                'verbose_name_plural': 'Essays',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('prize', models.CharField(blank=True, max_length=100, null=True)),
                ('word_limit', models.CharField(default='1500-2500', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('writing_mode', models.CharField(choices=[('normal', 'Normal'), ('paragraph', 'Paragraph by Paragraph')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_languages', models.ManyToManyField(blank=True, to='essay.language')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paragraph_number', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('word_count', models.IntegerField(default=0)),
                ('grammar_issues', models.PositiveIntegerField(default=0)),
                ('spelling_issues', models.PositiveIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='essay.essay')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essay.language')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_paragraphs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['paragraph_number'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='essay.competition')),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essay.essay')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('judge', 'Judge')], default='student', max_length=10)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('total_essays', models.IntegerField(default=0)),
                ('total_likes_received', models.IntegerField(default=0)),
                ('avg_essay_score', models.FloatField(default=0.0)),
                ('leaderboard_score', models.FloatField(default=0.0)),
                ('last_score_update', models.DateTimeField(blank=True, null=True)),
                ('competitions_entered', models.IntegerField(default=0)),
                ('competitions_won', models.IntegerField(default=0)),
                ('best_competition_rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essay.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='essay.essay')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['essay', '-created_at'], name='essay_comme_essay_i_03567c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='essay',
            index=models.Index(fields=['-created_at'], name='essay_essay_created_7ea0b8_idx'),
        ),
        migrations.AddIndex(
            model_name='essay',
            index=models.Index(fields=['status', '-created_at'], name='essay_essay_status_a49c06_idx'),
        ),
        migrations.AddIndex(
            model_name='essay',
            index=models.Index(fields=['author', '-created_at'], name='essay_essay_author__c6893c_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['-created_at'], name='essay_compe_created_c903e4_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['is_active', '-created_at'], name='essay_compe_is_acti_5291f3_idx'),
        ),
        migrations.AddIndex(
            model_name='paragraph',
            index=models.Index(fields=['essay', 'paragraph_number'], name='essay_parag_essay_i_c4118d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paragraph',
            unique_together={('essay', 'paragraph_number')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['competition', '-score'], name='essay_submi_competi_e0cf24_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_by', '-submitted_at'], name='essay_submi_submitt_a3f67a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('competition', 'submitted_by')},
        ),
    ]
