# Generated by Django 5.2.8 on 2025-12-29 07:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('grammar', 'Grammar'), ('spelling', 'Spelling'), ('structure', 'Structure'), ('content', 'Content'), ('style', 'Writing Style'), ('vocabulary', 'Vocabulary')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('correction', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'severity'],
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='essay',
            name='content_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='content_score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='essay',
            name='grammar_errors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='grammar_score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='essay',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='essay',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='essay',
            name='punctuation_errors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_essays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='essay',
            name='spelling_errors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='spelling_score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='essay',
            name='structure_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='style_suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_essays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='essay',
            name='vocabulary_suggestions',
            field=models.TextField(blank=True),
        ),
    ]
