# Generated by Django 5.2.8 on 2025-12-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='formatted_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='formatted_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='writing_mode',
            field=models.CharField(choices=[('normal', 'Normal Mode'), ('paragraph', 'Paragraph Mode')], default='paragraph', max_length=20),
        ),
    ]
