# Generated by Django 5.2.8 on 2026-01-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='grammar_errors_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='highlighted_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='overall_quality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='essay',
            name='ranking_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='ranking_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='essay',
            name='readability_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='essay',
            name='spelling_errors_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='style_suggestions_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
