# Generated by Django 5.2.8 on 2026-01-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0002_essay_grammar_errors_json_essay_highlighted_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
