# Generated by Django 5.2.8 on 2025-12-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0002_reviewtemplate_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='content_score',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='content_score_breakdown',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='grammar_score',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='grammar_score_breakdown',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='plagiarism_score',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='readability_score',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='spelling_score',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='spelling_score_breakdown',
        ),
        migrations.AddField(
            model_name='essay',
            name='emoji_feedback',
            field=models.CharField(blank=True, choices=[('🌟', '🌟 Excellent - Outstanding work!'), ('👍', '👍 Good - Well done!'), ('✅', '✅ Satisfactory - Meets expectations'), ('📝', '📝 Needs Improvement - Some areas to work on'), ('💡', '💡 Creative - Great ideas!'), ('🚀', '🚀 Impressive - Above and beyond'), ('🎯', '🎯 On Target - Meets all requirements'), ('🔥', '🔥 Amazing work!'), ('💫', '💫 Exceptional effort'), ('✨', '✨ Well crafted')], help_text='Overall feedback emoji', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
