# Generated by Django 5.2.8 on 2026-01-18 05:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0003_alter_essay_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'New Comment'), ('like', 'New Like'), ('system', 'System Notification'), ('achievement', 'Achievement Unlocked'), ('essay_published', 'Essay Published'), ('reply', 'Reply to Comment'), ('competition_start', 'Competition Started'), ('competition_result', 'Competition Result'), ('follow', 'New Follower')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('essay_score', models.FloatField(default=0.0, help_text='Average essay quality score')),
                ('grammar_score', models.FloatField(default=0.0, help_text='Average grammar score')),
                ('spelling_score', models.FloatField(default=0.0, help_text='Average spelling score')),
                ('vocabulary_score', models.FloatField(default=0.0, help_text='Vocabulary usage score')),
                ('essays_written', models.IntegerField(default=0)),
                ('essays_published', models.IntegerField(default=0)),
                ('essays_reviewed', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('percentile', models.FloatField(default=0.0)),
                ('badges_earned', models.IntegerField(default=0)),
                ('achievements_unlocked', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Total writing time in minutes')),
                ('total_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_score', '-essays_published'],
            },
        ),
    ]
